# Generated by Django 6.1.1 on 2026-09-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.CharField(help_text='URL or path to classroom photo', max_length=500)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in album')),
            ],
            options={
                'verbose_name': 'Classroom Photo',
                'verbose_name_plural': 'Classroom Photos',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(default='Fall 2026', max_length=100)),
                ('description', models.TextField(help_text='توضیحات درس')),
                ('characteristics', models.TextField(help_text='خصوصیات درس و موارد مرتبط')),
                ('telegram_channel', models.URLField(blank=True, help_text='لینک کانال تلگرام', null=True)),
                ('telegram_group', models.URLField(blank=True, help_text='لینک گروه تلگرام', null=True)),
                ('bale_link', models.URLField(blank=True, help_text='لینک بله', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Info',
                'verbose_name_plural': 'Course Info',
            },
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('lecture_notes', 'جزوات (Lecture Notes)'), ('assignment', 'تمرین ها (Assignments)'), ('quiz', 'کوییز ها (Quizzes)'), ('recitation', 'کلاس های تمرین (Recitation Classes)'), ('project', 'پروژه (Projects)'), ('sample_exam', 'نمونه سوال (Sample Exams)')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('file_url', models.CharField(help_text='Download URL or local server path', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course Material',
                'verbose_name_plural': 'Course Materials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeachingAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم شخص', max_length=150)),
                ('role', models.CharField(help_text='مسئولیت شخص در تیم', max_length=150)),
                ('email', models.EmailField(help_text='ایمیل', max_length=254)),
                ('telegram_id', models.CharField(help_text='ایدی تلگرام', max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('avatar_url', models.CharField(blank=True, help_text='Leave empty for default avatar', max_length=500, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Teaching Assistant',
                'verbose_name_plural': 'Teaching Assistants',
                'ordering': ['order', 'id'],
            },
        ),
    ]
