# Generated by Django 6.1.1 on 2026-09-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassroomPhoto',
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='CourseInfo',
        ),
        migrations.DeleteModel(
            name='TeachingAssistant',
        ),
        migrations.AlterModelOptions(
            name='coursematerial',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='category',
            field=models.CharField(choices=[('lecture_notes', 'جزوات'), ('assignment', 'تمرین ها'), ('quiz', 'کوییز ها'), ('recitation', 'کلاس های تمرین'), ('project', 'پروژه'), ('sample_exam', 'نمونه سوال')], max_length=50),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file_url',
            field=models.CharField(max_length=500),
        ),
    ]
