# Generated by Django 6.1.1 on 2026-09-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_classroomphoto_delete_contactmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='category',
            field=models.CharField(choices=[('lecture_notes', 'Lecture Notes'), ('assignment', 'Assignments'), ('quiz', 'Quizzes'), ('recitation', 'Recitation Classes'), ('project', 'Projects'), ('sample_exam', 'Sample Exams')], max_length=50),
        ),
    ]
