# Generated by Django 6.1.1 on 2026-09-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_coursematerial_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('assignment', 'Assignments / Homeworks'), ('quiz', 'Quizzes'), ('project', 'Projects'), ('sample_exam', 'Sample Exams'), ('lecture_note', 'Lecture Notes')], max_length=50)),
                ('description', models.CharField(blank=True, help_text='e.g. Due Oct 20th at 23:59', max_length=300)),
                ('file_url', models.CharField(help_text='Direct link or path for single-click download', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course File',
                'verbose_name_plural': 'Course Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecitationClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Recitation 1: Logic & Induction', max_length=200)),
                ('date_time', models.CharField(help_text='e.g. Mondays, 14:00 - 16:00', max_length=150)),
                ('location_or_link', models.CharField(help_text='Classroom number or online meeting link', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Session details or topics covered')),
                ('video_url', models.URLField(blank=True, help_text='Recording link if available', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recitation Class',
                'verbose_name_plural': 'Recitation Classes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CourseMaterial',
        ),
    ]
