# Generated by Django 6.1.1 on 2026-09-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_coursefile_recitationclass_delete_coursematerial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recitationclass',
            options={'ordering': ['id'], 'verbose_name': 'Recitation Class', 'verbose_name_plural': 'Recitation Classes'},
        ),
        migrations.AddField(
            model_name='coursefile',
            name='file_size',
            field=models.CharField(blank=True, help_text='e.g. 2.4 MB', max_length=20),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='file_type',
            field=models.CharField(default='PDF', help_text='e.g. PDF, ZIP', max_length=20),
        ),
        migrations.AddField(
            model_name='recitationclass',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g. 52 min', max_length=50),
        ),
        migrations.AddField(
            model_name='recitationclass',
            name='instructor',
            field=models.CharField(blank=True, help_text='e.g. Amir Jebbeli', max_length=150),
        ),
        migrations.AddField(
            model_name='recitationclass',
            name='number',
            field=models.CharField(blank=True, help_text='e.g. 01, 02', max_length=10),
        ),
        migrations.AlterField(
            model_name='recitationclass',
            name='date_time',
            field=models.CharField(blank=True, help_text='e.g. Mondays, 14:00 - 16:00', max_length=150),
        ),
        migrations.AlterField(
            model_name='recitationclass',
            name='location_or_link',
            field=models.CharField(blank=True, help_text='Classroom number or online meeting link', max_length=300),
        ),
    ]
