# Generated by Django 6.1.1 on 2026-09-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_recitationclass_options_coursefile_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefile',
            name='file',
            field=models.FileField(blank=True, help_text='Upload file directly from your computer', null=True, upload_to='course_files/'),
        ),
        migrations.AddField(
            model_name='recitationclass',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file directly from your computer', null=True, upload_to='recitation_videos/'),
        ),
        migrations.AlterField(
            model_name='coursefile',
            name='file_size',
            field=models.CharField(blank=True, help_text='Auto-calculated if file is uploaded', max_length=20),
        ),
        migrations.AlterField(
            model_name='coursefile',
            name='file_type',
            field=models.CharField(blank=True, default='PDF', help_text='e.g. PDF, ZIP', max_length=20),
        ),
        migrations.AlterField(
            model_name='coursefile',
            name='file_url',
            field=models.CharField(blank=True, help_text='External link or fallback path', max_length=500),
        ),
        migrations.AlterField(
            model_name='recitationclass',
            name='video_url',
            field=models.URLField(blank=True, help_text='External video link (YouTube, Aparat, Skyroom)', null=True),
        ),
    ]
