# Generated by Django 6.1.1 on 2026-09-30 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_coursefile_file_recitationclass_video_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursefile',
            options={'ordering': ['id'], 'verbose_name': 'Course File', 'verbose_name_plural': 'Course Files'},
        ),
        migrations.RemoveField(
            model_name='recitationclass',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='recitationclass',
            name='video_url',
        ),
        migrations.CreateModel(
            name='RecitationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, help_text='e.g. Worksheet & Solution Key', max_length=300)),
                ('file', models.FileField(blank=True, help_text='Upload file directly', null=True, upload_to='recitation_files/')),
                ('file_type', models.CharField(blank=True, default='PDF', help_text='e.g. PDF, ZIP', max_length=20)),
                ('file_size', models.CharField(blank=True, help_text='Auto-calculated if file is uploaded', max_length=20)),
                ('file_url', models.CharField(blank=True, help_text='External link or static fallback path', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.recitationclass')),
            ],
            options={
                'verbose_name': 'Recitation File',
                'verbose_name_plural': 'Recitation Files',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RecitationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, help_text='e.g. Full Session Live Recording', max_length=300)),
                ('video_file', models.FileField(blank=True, help_text='Upload MP4 video file', null=True, upload_to='recitation_videos/')),
                ('video_url', models.URLField(blank=True, help_text='External video link (YouTube, Aparat, Skyroom)', null=True)),
                ('duration', models.CharField(blank=True, help_text='e.g. 52 min', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.recitationclass')),
            ],
            options={
                'verbose_name': 'Recitation Video',
                'verbose_name_plural': 'Recitation Videos',
                'ordering': ['id'],
            },
        ),
    ]
