# Generated by Django 6.1.1 on 2026-09-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_coursefile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='📢 Course Announcement', help_text='Header tag/title e.g. 📌 Notice, 📢 Update', max_length=200)),
                ('message', models.TextField(help_text='Write any active announcement or notice for the Home page')),
                ('link', models.CharField(blank=True, help_text='Optional button link (URL or internal path e.g. /materials)', max_length=500)),
                ('link_text', models.CharField(blank=True, default='View Details', help_text='Button label', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide announcement on Home page')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page Announcement (Single Record)',
                'verbose_name_plural': 'Home Page Announcement (Single Record)',
            },
        ),
    ]
