# Generated by Django 6.1.1 on 2026-10-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_courseannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='recitationclass',
            name='instructor_telegram',
            field=models.CharField(blank=True, help_text='Telegram username or link for student Q&A e.g. @username', max_length=100),
        ),
    ]
