name: dm-website-dev

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dm-website-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./Front-end/src:/app/src
      - ./Front-end/public:/app/public
    environment:
      - NODE_ENV=development
